/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces_projet;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;

import client.MainClient;
import javax.swing.JSplitPane;

/**
 *
 * @author adrian
 */
public class Interface_Utilisateur_principale extends javax.swing.JFrame implements TreeSelectionListener{
	private static final long serialVersionUID = 1L;
	static String texteSaisieMessage = "Saisissez votre texte ici.";
	private UserPanel user;

	/**
	 * Creates new form JFrame
	 */
	public Interface_Utilisateur_principale(UserPanel user) {
		this.user = user;
		initComponents();
        this.setLocationRelativeTo(null);

		this.addWindowListener(new java.awt.event.WindowAdapter() {
			@Override
			public void windowClosing(java.awt.event.WindowEvent windowEvent) {
				if (JOptionPane.showConfirmDialog(null, "Are you sure to close the app?", "Really Closing?",
						JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
					// action on closing
					MainClient.close();
				}
			}
		});
		this.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		setPreferredSize(new Dimension(560, 560));
		
		arborescence = new javax.swing.JTree();
		
        setTitle("forum universite");

		DefaultMutableTreeNode top = new DefaultMutableTreeNode("Tickets");
		System.out.println(user);
		if (!user.getTicketList().isEmpty()) {
			for (TicketPanel ticket : user.getTicketList()) {
				DefaultMutableTreeNode ticketNode = new DefaultMutableTreeNode(ticket);
				/*if (!groupe.getTicketList().isEmpty()) {
					Iterable<TicketPanel> iterable3 = groupe.getTicketList();
					System.out.println("iterable3=" + iterable3.toString());
					for (TicketPanel ticket : iterable3) {
						DefaultMutableTreeNode treeNode3 = new DefaultMutableTreeNode(ticket.getName());
						treeNode2.add(treeNode3);
					}
				}*/
				top.add(ticketNode);
				
			}
		}
								
		splitPane = new JSplitPane();
		getContentPane().add(splitPane, BorderLayout.NORTH);
		leftJPanel = new javax.swing.JPanel();
		ticketScrollPane = new javax.swing.JScrollPane();
								
		leftJPanel.setAlignmentX(0.0F);
		leftJPanel.setAlignmentY(0.0F);
		leftJPanel.setPreferredSize(arborescence.getPreferredSize());
		leftJPanel.setLayout(new java.awt.BorderLayout());
										
		ticketScrollPane.setAlignmentX(0.0F);
		ticketScrollPane.setAutoscrolls(true);
		ticketScrollPane.setPreferredSize(new java.awt.Dimension(100, 400));
												
		arborescence = new JTree(top);
		arborescence.setAlignmentX(0.0F);
		arborescence.setAlignmentY(0.0F);
		arborescence.setAutoscrolls(true);
		//arborescence.setMaximumSize(new java.awt.Dimension(4000, 1000));
		//arborescence.setPreferredSize(new java.awt.Dimension(150, 300));
		arborescence.setScrollsOnExpand(true);
		arborescence.setToggleClickCount(1);
		arborescence.addTreeSelectionListener(this);
		
		ticketScrollPane.setViewportView(arborescence);
														
		leftJPanel.add(ticketScrollPane, java.awt.BorderLayout.CENTER);
		rightJPanel = new javax.swing.JPanel();
								
		rightJPanel.setLayout(new java.awt.BorderLayout());
										
		ticketViewer = 	new javax.swing.JScrollPane();
		ticketViewer.setPreferredSize(new Dimension(150, 460));
		ticketViewer.setViewportView(new TicketPanel(0, "", null, null, null));
		textPanel = new javax.swing.JScrollPane();
		saisieMessage = new javax.swing.JTextArea();
		
		saisieMessage.setColumns(20);
		saisieMessage.setRows(5);
		saisieMessage.setText(texteSaisieMessage);
		saisieMessage.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				saisieMessageMouseClicked(evt);
			}
		});
		textPanel.setViewportView(saisieMessage);
		
		rightJPanel.add(textPanel, java.awt.BorderLayout.CENTER);
		rightJPanel.add(ticketViewer, BorderLayout.NORTH);

		splitPane.setRightComponent(rightJPanel);
		splitPane.setLeftComponent(leftJPanel);

		pack();
	}// </editor-fold>//GEN-END:initComponents
	
	@Override
	public void valueChanged(TreeSelectionEvent e) {
		DefaultMutableTreeNode node =  (DefaultMutableTreeNode) arborescence.getLastSelectedPathComponent();
		try {
			TicketPanel t = (TicketPanel) node.getUserObject();
			displayTicket(t);
		} catch (ClassCastException ec) {
			// expected to happen when user click on top node
		} 
	}
	
	private void displayTicket(TicketPanel ticket) {
		ticketViewer.setViewportView(ticket);
		ticket.loadMessage();
		pack();
	}

	private void saisieMessageMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_saisieMessageMouseClicked

		Component component = evt.getComponent();
		if (saisieMessage.equals(component) && texteSaisieMessage.equals(saisieMessage.getText())) {
			saisieMessage.setText(null);
		}
	}// GEN-LAST:event_saisieMessageMouseClicked

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Interface_Utilisateur_principale.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Interface_Utilisateur_principale.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Interface_Utilisateur_principale.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Interface_Utilisateur_principale.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				List<TicketPanel> ticketList = new ArrayList<>();
				List<GroupPanel> groupList = new ArrayList<>();

				GroupPanel group = new GroupPanel(2, "Eleve");
				groupList.add(group);
				UserPanel Hugo = new UserPanel(1L, "ROUSSEL", "Hugo", "Eleve", ticketList, groupList);
				List<Long> messages = new ArrayList<>();
				ticketList.add(new TicketPanel(3L, "Test ticket", Hugo, group, messages));
				messages.add(32L);

				new Interface_Utilisateur_principale(Hugo).setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTree arborescence;
	private javax.swing.JPanel leftJPanel;
	private javax.swing.JPanel rightJPanel;
	private javax.swing.JScrollPane textPanel;
	private javax.swing.JScrollPane ticketViewer;
	private javax.swing.JScrollPane ticketScrollPane;
	private javax.swing.JTextArea saisieMessage;
	private JSplitPane splitPane;
	// End of variables declaration//GEN-END:variables

}
