/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces_projet;

import javax.swing.JOptionPane;

import packet.ContentType;
import utils.Id;

public class Interface_AddGroup extends javax.swing.JFrame {
	private static final long serialVersionUID = 1L;
	Interface_Serveur fenetreprincipale;
    /**
     * Creates new form Interface_AddGroup
     */
    public Interface_AddGroup( Interface_Serveur interfaceFenetre) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.fenetreprincipale = interfaceFenetre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        saisieNom = new javax.swing.JTextField();
        labelNom = new javax.swing.JLabel();
        boutonAnnuler = new javax.swing.JButton();
        boutonAddGroup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ajouter groupe");
        setAlwaysOnTop(true);
        setResizable(false);

        labelNom.setText("Nom");

        boutonAnnuler.setText("annuler");
        boutonAnnuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonAnnulerMouseClicked();
            }
        });

        boutonAddGroup.setText("creer groupe");
        boutonAddGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAddGroupActionPerformed();
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(boutonAnnuler)
                        .addGap(35, 35, 35)
                        .addComponent(boutonAddGroup))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(labelNom))
                            .addComponent(saisieNom, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelNom)
                .addGap(12, 12, 12)
                .addComponent(saisieNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boutonAnnuler)
                    .addComponent(boutonAddGroup))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void boutonAnnulerMouseClicked() {                                           
        this.dispose();
    }                                          
    
    private void boutonAddGroupActionPerformed() {                                               
       if(saisieNom.getText() != "") {
    	  if(1== fenetreprincipale.getDatabase().addgroup(Id.generate(ContentType.GROUP), saisieNom.getText())){
    		  JOptionPane.showMessageDialog(this.boutonAddGroup, "Groupe cree","",JOptionPane.INFORMATION_MESSAGE);
    		  fenetreprincipale.refreshPage2();
			  this.dispose();
    	  }
       }
        this.dispose();
    } 
   

    // Variables declaration - do not modify                     
    private javax.swing.JButton boutonAddGroup;
    private javax.swing.JButton boutonAnnuler;
    private javax.swing.JLabel labelNom;
    private javax.swing.JTextField saisieNom;
    // End of variables declaration                   
}
