
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces_projet;

import java.awt.Component;
import java.util.ArrayList;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle.ComponentPlacement;

import client.Categorie;
import packet.ContentType;
import server.Database;
import utils.Id;

/**
 *
 * @author adrian
 */
public class Interface_ModifUser extends javax.swing.JFrame {

	UserPanel user;
	Interface_Serveur fenetreprincipale;
	
    /**
     * Creates new form Interface_modifUser
     */
    public Interface_ModifUser(UserPanel user,Interface_Serveur interfaceFenetre) {
    	this.fenetreprincipale = interfaceFenetre;
    	this.user = user;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        labelMail = new javax.swing.JLabel();
        boutonAnnuler = new javax.swing.JButton();
        boutonAddUser = new javax.swing.JButton();
        saisieNom = new javax.swing.JTextField();
        labelNom = new javax.swing.JLabel();
        saisiePrenom = new javax.swing.JTextField();
        labelPrenom = new javax.swing.JLabel();
        saisieMDP = new javax.swing.JTextField();
        labelMdp = new javax.swing.JLabel();
        saisieMail = new javax.swing.JTextField();
        saisiecat = new javax.swing.JComboBox<>();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        setAlwaysOnTop(true);
        setResizable(false);
        
        
        
        labelMail.setText("adressse mail");
        saisieMail.setText(null);

        boutonAnnuler.setText("annuler");
        boutonAnnuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonAnnulerMouseClicked(evt);
            }
        });

        
        if (user.getId() == 0) {
        	boutonAddUser.setText("ajouter utilisateur");
        	setTitle("creation utilisateur");
        }else {
        	boutonAddUser.setText("modifier utilisateur");
        	setTitle("modification utilisateur");
        	saisieMail.setText(Database.recupMail(user.getId()));
        }
        	
        boutonAddUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonAddUserMouseClicked(evt);
            }
        });

        saisieNom.setText(user.getNom());
        
        labelNom.setText("Nom");

        saisiePrenom.setText(user.getPrenom());
        labelPrenom.setText("Prenom");

        labelMdp.setText("nouveau mot de passe");
        
        saisiecat.setModel(new javax.swing.DefaultComboBoxModel<>(Categorie.values()));
        saisiecat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            }
        });
        
        JLabel label = new JLabel();
        //TODO trouver mieux
        if (user.getId() != 0) {
        	label.setText("Categorie actuelle [ "+user.getCategory()+" ]");
        }else {
        	label.setText("Categorie");
        }
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(20)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(saisieNom, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
        						.addComponent(saisiePrenom, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(10)
        							.addComponent(labelPrenom))
        						.addComponent(saisiecat, GroupLayout.PREFERRED_SIZE, 202, GroupLayout.PREFERRED_SIZE)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(10)
        							.addComponent(label, GroupLayout.PREFERRED_SIZE, 320, GroupLayout.PREFERRED_SIZE))))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(29)
        					.addComponent(labelNom)))
        			.addPreferredGap(ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        					.addGroup(layout.createSequentialGroup()
        						.addGap(10)
        						.addComponent(labelMdp))
        					.addComponent(saisieMDP)
        					.addComponent(saisieMail, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(10)
        					.addComponent(labelMail)))
        			.addGap(20))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(34)
        			.addComponent(boutonAnnuler)
        			.addPreferredGap(ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
        			.addComponent(boutonAddUser)
        			.addGap(45))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(26)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(labelNom)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(saisieNom, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(labelMail)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(saisieMail, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(labelMdp)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(saisieMDP, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(labelPrenom)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(saisiePrenom, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addGap(18)
        			.addComponent(label)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(saisiecat, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(boutonAnnuler)
        				.addComponent(boutonAddUser))
        			.addContainerGap(30, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        

    private void boutonAnnulerMouseClicked(java.awt.event.MouseEvent evt) {                                           
        this.dispose();
    }                                          
    private void succes(String message) {
    	JOptionPane.showMessageDialog(this.boutonAddUser, message,
			    "",JOptionPane.INFORMATION_MESSAGE);
    }
    private void boutonAddUserMouseClicked(java.awt.event.MouseEvent evt) {  
    	 if(user.getId() == 0) {
    		if(saisieNom.getText() != "" && saisiePrenom.getText() != "" && saisieMDP.getText() !="" && saisieMail.getText() !="" ) {
    			if( 1==Database.addUser(Id.generate(ContentType.USER), saisieMDP.getText(), saisieNom.getText(), saisiePrenom.getText(), saisieMail.getText(), (Categorie)saisiecat.getSelectedItem())) {
    				succes("Utilisateur ajouté .");
    				fenetreprincipale.refreshPage1();
    				this.dispose();
    			}
    		}else {
    			JOptionPane.showMessageDialog(this.boutonAddUser, "Veuillez remplir toutes les cases.",
    				    "Erreur",JOptionPane.ERROR_MESSAGE);
    		}
    	}else {
    		
    		if (saisieMDP.getText() !="") {
    			Database.changePasswd(user.getId(), saisieMDP.getText());
    		}
    		if( 1==Database.changeUser(user.getId(), saisieNom.getText(), saisiePrenom.getText(), saisieMail.getText(), (Categorie)saisiecat.getSelectedItem())) {
    			succes("Utilisateur modifier .");
				fenetreprincipale.refreshPage1();
    			this.dispose();
    		}
    
    	}
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton boutonAddUser;
    private javax.swing.JButton boutonAnnuler;
    private javax.swing.JLabel labelNom;
    private javax.swing.JLabel labelPrenom;
    private javax.swing.JLabel labelMdp;
    private javax.swing.JLabel labelMail;
    private javax.swing.JTextField saisieMDP;
    private javax.swing.JTextField saisieMail;
    private javax.swing.JTextField saisieNom;
    private javax.swing.JTextField saisiePrenom;
    private javax.swing.JComboBox<Categorie> saisiecat;
}