/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces_projet;

import java.awt.event.ActionEvent;
import java.util.List;

import packet.Group;
import packet.User;
import server.Database;

/**
 *
 * @author adrian
 */
public class Interface_Serveur extends javax.swing.JFrame {

    /**
     * Creates new form Interface_Serveur
     */
    public Interface_Serveur() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	String url = "jdbc:mysql://eralyon.net:3306/projets5";
		String user = "projets5_server";
		String passwd = "projets5_psswd";
		Database.start(url,user,passwd);
        tableau = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        boutonAddUser = new javax.swing.JButton();
        boutonDelUser = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listUsers = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        groups = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeDesUtilisateurs = new javax.swing.JList<>();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listGroups = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        boutonAddGroup = new javax.swing.JButton();
        boutonDelGroup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("gestion du serveur");

        tableau.setAutoscrolls(true);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.GridLayout(1, 0, 2, 20));

        jPanel7.setLayout(new java.awt.GridLayout(2, 0));

        boutonAddUser.setText("ajouter un utilisateur");
        boutonAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	addUserActionPerformed(evt);
            }
        });
        jPanel7.add(boutonAddUser);

        boutonDelUser.setText("supprimer un utilisateur");
        jPanel7.add(boutonDelUser);

        jPanel6.add(jPanel7);

        jPanel2.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jButton3.setText("modifier");
        jPanel8.add(jButton3, java.awt.BorderLayout.PAGE_END);
       
        listUsers.setModel(new javax.swing.AbstractListModel<String>() {
        	List<User> listUser = Database.retrieveAllUser();       	
            public int getSize() { return listUser.size(); }
            public String getElementAt(int i) { return listUser.get(i).getPrenom()+" "+listUser.get(i).getNom();}
        });
        jScrollPane2.setViewportView(listUsers);

        jPanel8.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(jPanel5);

        tableau.addTab("Utilisateurs", jPanel1);

        groups.setLayout(new java.awt.GridLayout(1, 0));

        listeDesUtilisateurs.setModel(new javax.swing.AbstractListModel<String>() {
        	List<User> listUserg = Database.retrieveAllUser();
            public int getSize() { return listUserg.size(); }
            public String getElementAt(int i) { return listUserg.get(i).getPrenom()+" "+listUserg.get(i).getNom(); }
            public long getId(int i) { return listUserg.get(i).getId();}
        });
        jScrollPane1.setViewportView(listeDesUtilisateurs);

        groups.add(jScrollPane1);

        jPanel9.setLayout(new java.awt.GridLayout(4, 0));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel10);

        jPanel11.setLayout(new java.awt.BorderLayout());

        jButton1.setText("-- ajouter au groupe ->");
        jPanel11.add(jButton1, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel11);

        jPanel12.setLayout(new java.awt.BorderLayout());

        jButton2.setText("<- retirer du groupe --");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton2, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel12);

        jPanel13.setLayout(new java.awt.BorderLayout());
        jPanel9.add(jPanel13);

        groups.add(jPanel9);

        jPanel3.setLayout(new java.awt.BorderLayout());

        listGroups.setModel(new javax.swing.AbstractListModel<String>() {
            List<Group> ListGrp = Database.retrieveAllGroup();
            public int getSize() { return ListGrp.size(); }
            public String getElementAt(int i) { return ListGrp.get(i).getName(); }
            public long getidGrp(int i) { return ListGrp.get(i).getId();}
        });
        jScrollPane3.setViewportView(listGroups);

        jPanel3.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.GridLayout(2, 0));

        boutonAddGroup.setText("ajouter un groupe");
        jPanel4.add(boutonAddGroup);

        boutonDelGroup.setText("supprimer un groupe");
        jPanel4.add(boutonDelGroup);

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        groups.add(jPanel3);

        tableau.addTab("Groupes", groups);

        getContentPane().add(tableau, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    private void addUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaisieIntituleActionPerformed
        System.out.println("r"+listeDesUtilisateurs.getSelectedIndex());
    }//GEN-LAST:event_SaisieIntituleActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface_Serveur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface_Serveur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface_Serveur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface_Serveur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface_Serveur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonAddGroup;
    private javax.swing.JButton boutonAddUser;
    private javax.swing.JButton boutonDelGroup;
    private javax.swing.JButton boutonDelUser;
    private javax.swing.JPanel groups;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listGroups;
    private javax.swing.JList<String> listUsers;
    private javax.swing.JList<String> listeDesUtilisateurs;
    private javax.swing.JTabbedPane tableau;
    // End of variables declaration//GEN-END:variables
}
