/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces_projet;

import java.io.IOException;
import java.util.List;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.tree.DefaultMutableTreeNode;

import client.ClientDB;
import client.MainClient;
import packet.Commands;
import packet.Message;
import packet.Request;
import packet.Status;
import utils.Id;
import utils.StatusType;

public class Interface_MessageStatus extends javax.swing.JFrame {
	private static final long serialVersionUID = 1L;
	private MessagePanel message;
	private Status statusPacket;
    
    /**
     * Creates new form Interface_MessageStatus
     * @param message: message selectionné
     */
    public Interface_MessageStatus(MessagePanel message) {
    	//Update status
    	if(message.getStatus() != StatusType.USER_READ) {
			try {
				MainClient.comm.send(new Message(Commands.SEND, Id.DEFAULT_ID_STATUS, message.getId(), 0, 0, StatusType.USER_READ, null));
			} catch (IOException e1) {
				e1.printStackTrace();
			}
    	}
    	
        this.message=message;
        try {
			MainClient.comm.send(new Request((byte)(Commands.RETRIEVE | Commands.ALL), message.getId()));
			statusPacket = (Status) MainClient.comm.receive();
		} catch (IOException e) {
			e.printStackTrace();
		}
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageSelectionne = message;
        
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

		DefaultMutableTreeNode top = new DefaultMutableTreeNode("message");
		DefaultMutableTreeNode send = new DefaultMutableTreeNode("envoye");
		DefaultMutableTreeNode read = new DefaultMutableTreeNode("lu");
		DefaultMutableTreeNode pending = new DefaultMutableTreeNode("en attente");
		
		List<Long> listSend = statusPacket.getReceived();
		List<Long> listRead = statusPacket.getRead();
		List<Long> listPending = statusPacket.getPending();
		
		for (Long user : listSend) {
			DefaultMutableTreeNode leaf = new DefaultMutableTreeNode(ClientDB.findUser(user));
			send.add(leaf);
		}
		for (Long user : listRead) {
			DefaultMutableTreeNode leaf = new DefaultMutableTreeNode(ClientDB.findUser(user));
			read.add(leaf);
		}
		for (Long user : listPending) {
			DefaultMutableTreeNode leaf = new DefaultMutableTreeNode(ClientDB.findUser(user));
			pending.add(leaf);
		}
			
		top.add(read);
		top.add(send);
		top.add(pending);
		
		jTree1.setModel(new javax.swing.tree.DefaultTreeModel(top));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("status du message");
        setAlwaysOnTop(true);
        setResizable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap(20, Short.MAX_VALUE)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 356, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(33)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1.setLayout(jPanel1Layout);
        
        messageSelectionne.setVisible(true);
        jScrollPane1.setViewportView(messageSelectionne);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout(20, 20));

        jScrollPane3.setViewportView(jTree1);

        jPanel2.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private MessagePanel messageSelectionne;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
