/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces_projet;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

import utils.StatusType;

import java.awt.Color;

import javax.swing.GroupLayout;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JPanel;
import java.awt.BorderLayout;


public class MessagePanel extends javax.swing.JPanel {
	private static final long serialVersionUID = 1L;
	private long id;
	private String message;
	private long time;
	private byte status;
	private UserPanel user;
	
	
    @Override
	public String toString() {
		return "MessagePanel [id=" + id + ", message=" + message + ", time=" + time + ", status="+status+", user=" + user + "]";
	}

	/**
     * Creates new form Message
     */
	//TODO : ajouter Ticket
    public MessagePanel(long id, long time, UserPanel user, byte status, String message) {
		setPreferredSize(new Dimension(300, 100));
    	this.id = id;
    	this.time = time;
    	this.user = user;
    	this.message = message;
    	this.status = status;
        initComponents();
        
        updateDisplayedData();
    }
    
    public String getMessage() {
		return message;
	}
    public byte getStatus() {
    	return status;
    }
	public long getTime() {
		return time;
	}

	public UserPanel getUser() {
		return user;
	}

	public javax.swing.JTextArea getTextMessage() {
		return textMessage;
	}

	public javax.swing.JLabel getNomCreateur() {
		return nomCreateur;
	}

	public long getId() {
    	return id;
    }
    public void updateDisplayedData() {
    	nomCreateur.setText(user.getName()); //TODO better use of user jpanel
        dateCreation.setText(new java.util.Date((long)time*1000).toString());
        textMessage.setText(message);
        updateColor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        topPanel.setPreferredSize(new Dimension(300, 40));
        nomCreateur = new javax.swing.JLabel();
        nomCreateur.setFont(new Font("Tahoma", Font.BOLD, 12));
        dateCreation = new javax.swing.JLabel();
        dateCreation.setFont(new Font("Tahoma", Font.PLAIN, 10));
        dateCreation.setForeground(Color.DARK_GRAY);

        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanelLayout.setHorizontalGroup(
        	topPanelLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(topPanelLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(topPanelLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(nomCreateur)
        				.addComponent(dateCreation))
        			.addContainerGap(141, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
        	topPanelLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(topPanelLayout.createSequentialGroup()
        			.addGap(6)
        			.addComponent(nomCreateur)
        			.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addComponent(dateCreation))
        );
        topPanel.setLayout(topPanelLayout);

        add(topPanel, java.awt.BorderLayout.PAGE_START);
        
        textPanel = new JPanel();
        add(textPanel, BorderLayout.CENTER);
        textPanel.setLayout(new BorderLayout(0, 0));
        textMessage = new javax.swing.JTextArea();
        textMessage.setLineWrap(true);
        textPanel.add(textMessage);
        
        textMessage.setEditable(false);
        textMessage.setColumns(20);
        textMessage.setRows(5);
        
        java.awt.event.MouseAdapter evtClick = new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onClick();
            }
        };
        textMessage.addMouseListener(evtClick);
        this.addMouseListener(evtClick);
    }// </editor-fold>//GEN-END:initComponents

    public void updateColor() {
    	switch(status) {
    	case StatusType.MESSAGE_PENDING :
    		topPanel.setBackground(StatusType.COLOR_MESSAGE_PENDING);
    		break;
    	case StatusType.USER_PENDING :
    		topPanel.setBackground(StatusType.COLOR_USER_PENDING);
    		break;
    	case StatusType.USER_SENT :
    		topPanel.setBackground(StatusType.COLOR_USER_SENT);
    		break;
    	case StatusType.USER_READ :
    		topPanel.setBackground(StatusType.COLOR_USER_READ);
    		break;
    	default :
    		System.err.println("MessagePanel : unknow status");
    	}
    }

    public void onClick() {
    	new Interface_MessageStatus(this).setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea textMessage;
    private javax.swing.JLabel dateCreation;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel nomCreateur;
    private JPanel textPanel;
    // End of variables declaration//GEN-END:variables
}
