/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces_projet;

/**
 *
 * @author adrian
 */
public class MessagePanel extends javax.swing.JPanel {
	private static final long serialVersionUID = 1L;
	private long id;
	private String message;
	private long time;
	private UserPanel user;
	

    /**
     * Creates new form Message
     */
    public MessagePanel(long id, long time, UserPanel user, String message) {
    	this.id = id;
    	this.time = time;
    	this.user = user;
    	this.message = message;
    	
        initComponents();
        
        updateDisplayedData();
    }
    
    public long getId() {
    	return id;
    }
    
    private void updateDisplayedData() {
    	nomCreateur.setText(user.getName()); //TODO better use of user jpanel
        dateCreation.setText(new java.util.Date((long)time*1000).toString());
        TextMessage.setText(message);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nomCreateur = new javax.swing.JLabel();
        dateCreation = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextMessage = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(nomCreateur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addComponent(dateCreation)
                .addGap(70, 70, 70))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomCreateur)
                    .addComponent(dateCreation))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        TextMessage.setEditable(false);
        TextMessage.setColumns(20);
        TextMessage.setRows(5);
        jScrollPane1.setViewportView(TextMessage);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextMessage;
    private javax.swing.JLabel dateCreation;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nomCreateur;
    // End of variables declaration//GEN-END:variables
}
